version: '3.9'

services:
  web:
    build: .
    container_name: book_review_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind :8000 --workers 2 config.wsgi"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: book_review_db
    restart: always
    environment:
      MYSQL_DATABASE: bookdb
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: bookpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  static_volume:
